name: CI

on: [push, pull_request]

jobs:
  presubmit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: yarn

    - name: Presubmit
      run: gulp presubmit
